version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - SERVICE_NAME=api-gateway
    depends_on:
      - redis
    networks:
      - microservices-network

  # Syllabus Service
  syllabus-service:
    build:
      context: .
      dockerfile: syllabus-service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - SERVICE_NAME=syllabus-service
      - DATABASE_URL=mysql+pymysql://root:password@syllabus-db:3306/syllabus_db
    depends_on:
      - syllabus-db
      - redis
    networks:
      - microservices-network

  # Subject Service
  subject-service:
    build:
      context: .
      dockerfile: subject-service/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - SERVICE_NAME=subject-service
      - DATABASE_URL=mysql+pymysql://root:password@subject-db:3306/subject_db
    depends_on:
      - subject-db
      - redis
    networks:
      - microservices-network

  # File Service
  file-service:
    build:
      context: .
      dockerfile: file-service/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
      - SERVICE_NAME=file-service
      - DATABASE_URL=mysql+pymysql://root:password@file-db:3306/file_db
    depends_on:
      - file-db
      - redis
    networks:
      - microservices-network

  # Configuration Service
  config-service:
    build:
      context: .
      dockerfile: config-service/Dockerfile
    ports:
      - "8004:8004"
    environment:
      - PORT=8004
      - SERVICE_NAME=config-service
      - DATABASE_URL=mysql+pymysql://root:password@config-db:3306/config_db
    depends_on:
      - config-db
      - redis
    networks:
      - microservices-network

  # Databases
  syllabus-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=syllabus_db
    ports:
      - "3307:3306"
    volumes:
      - syllabus_data:/var/lib/mysql
    networks:
      - microservices-network

  subject-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=subject_db
    ports:
      - "3308:3306"
    volumes:
      - subject_data:/var/lib/mysql
    networks:
      - microservices-network

  file-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=file_db
    ports:
      - "3309:3306"
    volumes:
      - file_data:/var/lib/mysql
    networks:
      - microservices-network

  config-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=config_db
    ports:
      - "3310:3306"
    volumes:
      - config_data:/var/lib/mysql
    networks:
      - microservices-network

  # Message Broker
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - microservices-network

volumes:
  syllabus_data:
  subject_data:
  file_data:
  config_data:
  redis_data:

networks:
  microservices-network:
    driver: bridge